name: websocket_client
description: Open source multiplatform  websocket client.
publish_to: 'none' 
version: 0.2.0
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  flutter_chat_bubble: ^2.0.2
  bitsdojo_window: ^0.1.5
  desktop_window:
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # https://flutter.dev/assets-and-images/
  # https://flutter.dev/assets-and-images/
  # see https://flutter.dev/custom-fonts/
